### ISSUE TITLE
light sensor returns empty value

### ISSUE THREAD

**Issue by chiragparekh** [Cshayan/react-native-ambient-light-sensor#1]
Hi, I have created new react native app and installed this package, I am using the example code from the readme file. 

When I run the code light sensor returns empty value. I am currently testing on the physical device.

Do I need to configure anything else?

**Comment by Mladen1kus** [comment]
@chiragparekh this module works only for android platform, iOS code is missing, maybe that's your issue. Also, the correct event listener name is LightSensor not LIGHT_SENSOR.

**Comment by chiragparekh** [comment]
@Mladen1kus I was testing with android device I wasn't able to make it work.

**Comment by Mladen1kus** [comment]
@chiragparekh Try changing the LIGHT_SENSOR event name to LightSensor, it won't work without that change(example code is wrong)

**Comment by Cshayan** [comment]
@Mladen1kus thanks for pointing out. Yes the event name should be `LightSensor`. I will make the change in readme.

@chiragparekh check if you are receiving the value after making the above change. After that we can close this.

**Comment by Mladen1kus** [comment]
@Cshayan do you happen to know if this is possible to do on iOS side?

**Comment by Cshayan** [comment]
@Mladen1kus I am not so much into iOS ecosystem. But I believe it can be done using Sensorkit framework.

https://developer.apple.com/documentation/sensorkit

Feel free to raise a PR for iOS functonality if you want to contribute.
