### ISSUE TITLE
Feature request: Check if Ambient light sensor is presented

### ISSUE THREAD

**Issue by kvs-coder** [Cshayan/react-native-ambient-light-sensor#2]
Thank you for your library! 

I was wondering, if it is possible to have a method which will returns the bool value stating if the sensor is available on the device or no?

For instance some Android devices (like tablets) might not have an integrated ambient light sensor. In this case business logic of the app should behave differently

**Comment by kvs-coder** [comment]
@Cshayan  Please review this small one PR 

https://github.com/Cshayan/react-native-ambient-light-sensor/pull/3

**Comment by Cshayan** [comment]
@kvs-coder thanks for the PR. The PR is merged. Closing this.

Thanks!
